apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: nginx
          image: httpd
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
              protocol: TCP
